spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  secret:
    key: ${jwt.secret.key}

ocr:
  secret:
    key: ${ocr.secret.key}
  url: ${ocr.url}
