spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

## s3설정
cloud:
  aws:
    credentials:
      access-key: ${AWS.S3.ACCESS.KEY.ID}
      secret-key: ${AWS.S3.SECRET.ACCESS.KEY}
    s3:
      bucket: homeat-dev-s3
    stack:
      auto: false
    region:
      static: ap-northeast-2

jwt:
  secret:
    key: ${jwt.secret.key}

ocr:
  secret:
    key: ${ocr.secret.key}
  url: ${ocr.url}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${mail.username}
  password: ${mail.password}
  properties:
    mail:
      debug: true
      smtp:
        auth: true
        starttls.enable: true
        starttls.required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR